{{ if and (index .Values "loki" "localpvScConfig" "enabled") (index .Values "loki" "enabled") }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: {{ tpl (( index .Values "loki" "localpvScConfig" "basePath" ) | quote ) . }}
    openebs.io/cas-type: local
  name: {{ (tpl (index .Values "loki" "localpvScConfig" "name") .) | required (print "StorageClass name for loki localpv storage cannot be empty") }}
provisioner: openebs.io/local
reclaimPolicy: {{ (index .Values "loki" "localpvScConfig" "reclaimPolicy") }}
volumeBindingMode: {{ (index .Values "loki" "localpvScConfig" "volumeBindingMode") }}
{{ end }}
